-- Oracle 19c Schema for Conference Paper Submission Portal

-- Drop tables if they exist (Oracle style)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE papers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE paper_status CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE conferences CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Create Tables
CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname       VARCHAR2(100) NOT NULL,
    email          VARCHAR2(100) UNIQUE NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    role           VARCHAR2(20) CHECK (role IN ('student', 'faculty', 'admin', 'reviewer')),
    institution    VARCHAR2(100),
    department     VARCHAR2(100),
    created_date   DATE DEFAULT SYSDATE
);

CREATE TABLE conferences (
    conference_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conference_name      VARCHAR2(200) NOT NULL,
    conference_date      DATE NOT NULL,
    submission_deadline  DATE NOT NULL,
    location             VARCHAR2(100),
    description          CLOB,
    max_papers_per_user  NUMBER DEFAULT 3,
    is_active            NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
);

CREATE TABLE paper_status (
    status_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name  VARCHAR2(50) NOT NULL,
    description  VARCHAR2(200)
);

CREATE TABLE papers (
    paper_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR2(500) NOT NULL,
    abstract          CLOB,
    keywords          VARCHAR2(500),
    submission_date   DATE DEFAULT SYSDATE,
    last_modified     DATE DEFAULT SYSDATE,
    submitter_id      NUMBER REFERENCES users(user_id),
    conference_id     NUMBER REFERENCES conferences(conference_id),
    status_id         NUMBER REFERENCES paper_status(status_id),
    file_path         VARCHAR2(500),
    file_name         VARCHAR2(200),
    valid_submission  NUMBER(1) DEFAULT 1 CHECK (valid_submission IN (0, 1)),
    review_score      NUMBER(3,2),
    final_decision    VARCHAR2(50)
);

-- Insert Initial Data
INSERT INTO paper_status (status_name, description) VALUES ('Submitted', 'Paper awaiting review');
INSERT INTO paper_status (status_name, description) VALUES ('Under Review', 'Paper is currently being reviewed');
INSERT INTO paper_status (status_name, description) VALUES ('Accepted', 'Paper accepted for publication');
INSERT INTO paper_status (status_name, description) VALUES ('Rejected', 'Paper was not accepted');

INSERT INTO users (fullname, email, password_hash, role, institution, department)
VALUES ('Rahul S', 'rahul@example.com', 'hash1', 'student', 'Tech University', 'CS');
INSERT INTO users (fullname, email, password_hash, role, institution, department)
VALUES ('Sneha I', 'sneha@example.com', 'hash2', 'student', 'Tech University', 'IT');
INSERT INTO users (fullname, email, password_hash, role, institution, department)
VALUES ('Priya K', 'priya@example.com', 'hash3', 'faculty', 'Tech University', 'CS');

INSERT INTO conferences (conference_name, conference_date, submission_deadline, location, description)
VALUES ('AI Conference', TO_DATE('2025-09-15', 'YYYY-MM-DD'), TO_DATE('2025-08-31', 'YYYY-MM-DD'), 'Chennai', 'Focus on AI techniques.');
INSERT INTO conferences (conference_name, conference_date, submission_deadline, location, description)
VALUES ('Cybersecurity Summit', TO_DATE('2025-10-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'), 'Delhi', 'Latest in cybersecurity.');

INSERT INTO papers (title, abstract, keywords, submission_date, last_modified, submitter_id, conference_id, status_id, file_path, file_name)
VALUES ('AI in Medicine', 'Paper about AI in healthcare.', 'AI, Medicine', TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD'), 1, 1, 1, '/files/ai_medicine.pdf', 'ai_medicine.pdf');
INSERT INTO papers (title, abstract, keywords, submission_date, last_modified, submitter_id, conference_id, status_id, file_path, file_name)
VALUES ('Network Security Advances', 'Paper on new security protocols.', 'Security, Networks', TO_DATE('2025-08-12', 'YYYY-MM-DD'), TO_DATE('2025-08-12', 'YYYY-MM-DD'), 2, 2, 2, '/files/network_security.pdf', 'network_security.pdf');

COMMIT;

-- Trigger to update last_modified
CREATE OR REPLACE TRIGGER trg_papers_last_modified
BEFORE UPDATE ON papers
FOR EACH ROW
BEGIN
    :NEW.last_modified := SYSDATE;
END;
/

-- Procedure to submit paper with validation
CREATE OR REPLACE PROCEDURE submit_paper(
    p_title         IN VARCHAR2,
    p_abstract      IN CLOB,
    p_keywords      IN VARCHAR2,
    p_submitter_id  IN NUMBER,
    p_conference_id IN NUMBER,
    p_file_path     IN VARCHAR2,
    p_file_name     IN VARCHAR2
) AS
    v_max_papers  NUMBER;
    v_user_papers NUMBER;
BEGIN
    SELECT max_papers_per_user INTO v_max_papers
    FROM conferences
    WHERE conference_id = p_conference_id;

    SELECT COUNT(*) INTO v_user_papers
    FROM papers
    WHERE submitter_id = p_submitter_id
      AND conference_id = p_conference_id;

    IF v_user_papers >= v_max_papers THEN
        RAISE_APPLICATION_ERROR(-20001, 'User has reached the maximum paper submissions for this conference.');
    ELSE
        INSERT INTO papers (title, abstract, keywords, submitter_id, conference_id, status_id, file_path, file_name)
        VALUES (p_title, p_abstract, p_keywords, p_submitter_id, p_conference_id, 1, p_file_path, p_file_name);
    END IF;
END;
/

-- Procedure to change paper status
CREATE OR REPLACE PROCEDURE change_paper_status(
    p_paper_id   IN NUMBER,
    p_new_status IN NUMBER
) AS
BEGIN
    UPDATE papers
    SET status_id = p_new_status
    WHERE paper_id = p_paper_id;
END;
/
